_target_: perceptual_metrics.models.svg_prime_interface.SVGPrimeInterface
checkpoint_dir: [/viscam/projects/objectfolder_benchmark/Robot_related/Taxim_obj/svg-prime/svg_prime/logs/surface_trav/56/t/model_38.pth, /viscam/projects/objectfolder_benchmark/Robot_related/Taxim_obj/svg-prime/svg_prime/logs/surface_trav/56/t/model_38.pth]
n_past: 2
planning_modalities: ${planning_modalities}
epoch: null