defaults:
  - objective: mse_rgb
  - sampler: correlated_noise

_target_: perceptual_metrics.mpc.cem.CEMOptimizer
a_dim: ${env.a_dim}
num_samples: 200
horizon: ${planning_horizon}
opt_iters: 3
init_std: [0.5, 0.5, 0, 0]
elites_frac: 0.05
gamma: None