defaults:
  - objective: mse_rgb

_target_: perceptual_metrics.mpc.cem.CEMOptimizer
sampler:
  _target_: perceptual_metrics.mpc.sampler.CorrelatedNoiseSampler
  a_dim: ${a_dim}
  beta: 0.3
  horizon: ${planning_horizon}
a_dim: ${a_dim}
num_samples: 256
horizon: ${planning_horizon}
opt_iters: 3
#init_std: [0.035, 0.035, 0.08, 0.1745, 0.0]
#init_std: [0.05, 0.05, 0.08, 0.1745, 0.0]
#init_std: [0.05, 0.05, 0.08, 0.1745, 0.0]
init_std: [0.05, 0.05, 0.08, 0.1745, 2]
init_mean: [0, 0, -0.05, 0, 0]
elites_frac: 0.05
round_gripper_action: True