_target_: perceptual_metrics.mpc.objectives.CombinedObjective
objectives:
  rgb:
    _target_: perceptual_metrics.mpc.objectives.SquaredError
    key: rgb
    weight: 1
  depth:
    _target_: perceptual_metrics.mpc.objectives.SquaredError
    key: depth
    weight: 3
  normal:
    _target_: perceptual_metrics.mpc.objectives.SquaredError
    key: normal
    weight: 1
